cc_binary(
    name = "hello_world_c",
    srcs = ["hello_world.c"],
)

cc_binary(
    name = "hello_world_cc",
    srcs = ["hello_world.cc"],
)

py_binary(
    name = "hello_world_py",
    main = "hello_world.py",
    srcs = ["hello_world.py"],
)
